// <auto-generated />
using System;
using HReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HReport.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HReport.Models.InfoReport", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("InfoReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Complaint = "Complaint 1",
                            Date = new DateTime(2024, 9, 17, 12, 12, 5, 906, DateTimeKind.Utc).AddTicks(4482),
                            Description = "Description 1",
                            IsChecked = false
                        },
                        new
                        {
                            Id = 2,
                            Complaint = "Complaint 2",
                            Date = new DateTime(2024, 9, 17, 12, 12, 5, 906, DateTimeKind.Utc).AddTicks(4488),
                            Description = "Description 2",
                            IsChecked = false
                        },
                        new
                        {
                            Id = 3,
                            Complaint = "Complaint 3",
                            Date = new DateTime(2024, 9, 17, 12, 12, 5, 906, DateTimeKind.Utc).AddTicks(4489),
                            Description = "Description 3",
                            IsChecked = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
